### PR TITLE
Use a pseudo-groupMap instead of collect to look up alias owners. WA-48

### PR DESCRIPTION
**Pull request by kshakir**
- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Make sure Swagger is updated if API changes
- [ ] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] Tell the tech lead (TL) that the PR exists if they wants to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via Slack and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by kshakir** [comment]
Deployed `0e68b89` to `perf`, ran mcnulty with `SBT_OPTS="-Dconcurrency=50 -DnumSeconds=300 -Denv=perf" sbt compile "gatling:testOnly *AgoraGetAllSimulation"`.

Results:
```
================================================================================
---- Global Information --------------------------------------------------------
> request count                                        100 (OK=100    KO=0     )
> min response time                                   2460 (OK=2460   KO=-     )
> max response time                                  16364 (OK=16364  KO=-     )
> mean response time                                  7265 (OK=7265   KO=-     )
> std deviation                                       4048 (OK=4048   KO=-     )
> response time 50th percentile                       9775 (OK=9775   KO=-     )
> response time 75th percentile                      10952 (OK=10952  KO=-     )
> response time 95th percentile                      12042 (OK=12042  KO=-     )
> response time 99th percentile                      13944 (OK=13944  KO=-     )
> mean requests/sec                                  0.325 (OK=0.325  KO=-     )
---- Response Time Distribution ------------------------------------------------
> t < 800 ms                                             0 (  0%)
> 800 ms < t < 1200 ms                                   0 (  0%)
> t > 1200 ms                                          100 (100%)
> failed                                                 0 (  0%)
================================================================================
```

**Review by aednichols — APPROVED** [review]
Wow!

**Review by davidangb — APPROVED** [review]
did not test, but changes lgtm! :+1: nice find

**Review by salonishah11 — APPROVED** [review]
🎉

**Pull request merged**
