### PR TITLE
GAWB-3548 Make root entity type not required for published configs

### PR DESCRIPTION
**Pull request by breilly2**
- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Make sure Swagger is updated if API changes
- [ ] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] Tell the tech lead (TL) that the PR exists if they wants to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via Slack and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Review by helgridly — APPROVED** [review]
Looks good. And optional-ising is a nonbreaking change, which is great. Is there Swagger to update here? And you might want to check the import path into Rawls if you haven't already, though I _think_ it should work.

**Comment by breilly2** [comment]
Annoyingly (for me anyway... as someone who had never tried to use agora's swagger before), there wasn't any mention in swagger of the expected properties for a config. It's all in the payload which is just a string that is later interpreted as JSON. What actually happened is that I was able to create a config with _none_ of the "required" properties. The error wasn't reported until I tried to read the config back out.

Incidentally, I've done this in the dev DB(s) (I think... agora uses mysql _and_ mongo?) and I don't know how to reach into the database to clean it up.

What's the import path into rawls? Have I tested this by exercising the UI to publish a rootless config and importing it back into a workspace?

**Comment by helgridly** [comment]
> What's the import path into rawls? Have I tested this by exercising the UI to publish a rootless config and importing it back into a workspace?

Yes, you have :)

**Review by ahaessly — APPROVED** [review]
👍

**Comment by breilly2** [comment]
Jenkins retest because the agora build failed for external reasons.

**Pull request merged**
