### PR TITLE
upgrade java libs to cromwell 34

### PR DESCRIPTION
**Pull request by davidangb**
adopt the cromwell 34 library.

this is untested beyond unit/automation tests.

### CODE REVIEW

**Comment by davidangb** [comment]
automation failed trying to download dependencies. This should be transient. Jenkins retest.

**Comment by davidangb** [comment]
This passed all automation tests except SignInSpec, which failed due to Google challenging us to prove we're not robots. I'm calling it a pass.

**Review by jmthibault79 — APPROVED** [review]
Confirmed hash = 34 release tag

**Comment by davidangb** [comment]
jenkins failed downloading Jackson and scala compiler. This should be transient. Jenkins retest.

**Pull request merged**
