### PR TITLE
Enable Docker Content Trust Signing for Images

### PR DESCRIPTION
**Pull request by rmeffan**
### I. Notes
1. This PR addresses findings described in FedRAMP CM-5(3). Related JIRA issue is DDO-866.
2. This PR is 3 of 3 that collectively implement the first pass of Docker Content Trust (DCT) docker image signing and verification. NOTE: All three PRs must be merged and their changes must be deployed concurrently.
3. When the three PRs are merged, and the Jenkins DSL job changes have been deployed, the following Terra/FC app(s) will use DCT image signing and verification for their docker image builds and for image deployments in the specified Terra/FC environment(s):
    - agora, dev 
4. This PR modifies the following script that will invoke the Docker Content Trust image signing process:
    - `docker/build.sh`
        - Add function `docker_content_trust_sign_app_image`.
        - Replace `gcloud docker -- push` with `docker_content_trust_sign_app_image` call.
5. Related PRs:
    - https://github.com/broadinstitute/firecloud-develop/pull/2338
    - https://github.com/broadinstitute/dsp-jenkins/pull/463 

### II. Agora PR Checklist Items from Template
- [x] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Make sure Swagger is updated if API changes
- [ ] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [x] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] Tell the tech lead (TL) that the PR exists if they wants to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via Slack and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Review by choover-broad — APPROVED** [review]
TIL about `:?` syntax in shell variables -- nice!

**Comment by rmeffan** [comment]
@davidangb @kshakir @aednichols, this PR is ready to be merged. It doesn't change anything about agora; the change enables docker image signing, so the effective change is that it will replace the docker push to GCR for agora images.

I reviewed the checklist, but it seems like most of it would not be applicable to this type of change. Obviously, any build related items (such as testing and verifying that the build and push work properly) would still apply.

Would be great to get your thoughts about the above. Thanks!

**Review by kshakir — COMMENTED** [review]
Thanks for the PR @rmeffan. Will leave it to @aednichols and the other Agora owners to review and reach out if they need more assistance.

**Comment by davidangb** [comment]
seconding what Khalid said ... since this is specific to Agora, I'll defer to the Agora team's reviews

**Review by davidangb — COMMENTED** [review]
leaving a comment so it stops bugging me for a review!

**Review by aednichols — APPROVED** [review]
I don't know that much about Docker but I can approve this from the perspective that it's not going to alter the correctness or security of Agora itself 👍

**Pull request merged**
